[build]
  command = "echo 'Aucun build nécessaire'"  # Désactive toute commande de build
  publish = ""  # Désactive le déploiement du site
  functions = "netlify/functions"  # Dossier des fonctions

[functions]
  node_bundler = "nft"  # Utilise le bundler intégré de Netlify
